In [1]:
import pandas as pd
data = pd.read_csv("dc-wikia-data.csv")

In [2]:
data

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,YEAR
0,1422,Batman (Bruce Wayne),\/wiki\/Batman_(Bruce_Wayne),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3093.0,"1939, May",1939.0
1,23387,Superman (Clark Kent),\/wiki\/Superman_(Clark_Kent),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2496.0,"1986, October",1986.0
2,1458,Green Lantern (Hal Jordan),\/wiki\/Green_Lantern_(Hal_Jordan),Secret Identity,Good Characters,Brown Eyes,Brown Hair,Male Characters,NaN,Living Characters,1565.0,"1959, October",1959.0
3,1659,James Gordon (New Earth),\/wiki\/James_Gordon_(New_Earth),Public Identity,Good Characters,Brown Eyes,White Hair,Male Characters,NaN,Living Characters,1316.0,"1987, February",1987.0
4,1576,Richard Grayson (New Earth),\/wiki\/Richard_Grayson_(New_Earth),Secret Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,1237.0,"1940, April",1940.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6891,66302,Nadine West (New Earth),\/wiki\/Nadine_West_(New_Earth),Public Identity,Good Characters,NaN,NaN,Female Characters,NaN,Living Characters,NaN,NaN,NaN
6892,283475,Warren Harding (New Earth),\/wiki\/Warren_Harding_(New_Earth),Public Identity,Good Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
6893,283478,William Harrison (New Earth),\/wiki\/William_Harrison_(New_Earth),Public Identity,Good Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
6894,283471,William McKinley (New Earth),\/wiki\/William_McKinley_(New_Earth),Public Identity,Good Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
6895,150660,Mookie (New Earth),\/wiki\/Mookie_(New_Earth),Public Identity,Bad Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,NaN,NaN,NaN

In [3]:
data.head

<bound method NDFrame.head of       page_id                          name  \
0        1422          Batman (Bruce Wayne)
1       23387         Superman (Clark Kent)
2        1458    Green Lantern (Hal Jordan)
3        1659      James Gordon (New Earth)
4        1576   Richard Grayson (New Earth)
...       ...                           ...
6891    66302       Nadine West (New Earth)
6892   283475    Warren Harding (New Earth)
6893   283478  William Harrison (New Earth)
6894   283471  William McKinley (New Earth)
6895   150660            Mookie (New Earth)

                                   urlslug               ID            ALIGN  \
0             \/wiki\/Batman_(Bruce_Wayne)  Secret Identity  Good Characters
1            \/wiki\/Superman_(Clark_Kent)  Secret Identity  Good Characters
2       \/wiki\/Green_Lantern_(Hal_Jordan)  Secret Identity  Good Characters
3         \/wiki\/James_Gordon_(New_Earth)  Public Identity  Good Characters
4      \/wiki\/Richard_Grayson_(New_Earth)  Secret Identity  Good Characters
...                                    ...              ...              ...
6891       \/wiki\/Nadine_West_(New_Earth)  Public Identity  Good Characters
6892    \/wiki\/Warren_Harding_(New_Earth)  Public Identity  Good Characters
6893  \/wiki\/William_Harrison_(New_Earth)  Public Identity  Good Characters
6894  \/wiki\/William_McKinley_(New_Earth)  Public Identity  Good Characters
6895            \/wiki\/Mookie_(New_Earth)  Public Identity   Bad Characters

             EYE        HAIR                SEX  GSM              ALIVE  \
0      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
1      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
2     Brown Eyes  Brown Hair    Male Characters  NaN  Living Characters
3     Brown Eyes  White Hair    Male Characters  NaN  Living Characters
4      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
...          ...         ...                ...  ...                ...
6891         NaN         NaN  Female Characters  NaN  Living Characters
6892         NaN         NaN    Male Characters  NaN  Living Characters
6893         NaN         NaN    Male Characters  NaN  Living Characters
6894         NaN         NaN    Male Characters  NaN  Living Characters
6895   Blue Eyes  Blond Hair    Male Characters  NaN  Living Characters

      APPEARANCES FIRST APPEARANCE    YEAR
0          3093.0        1939, May  1939.0
1          2496.0    1986, October  1986.0
2          1565.0    1959, October  1959.0
3          1316.0   1987, February  1987.0
4          1237.0      1940, April  1940.0
...           ...              ...     ...
6891          NaN              NaN     NaN
6892          NaN              NaN     NaN
6893          NaN              NaN     NaN
6894          NaN              NaN     NaN
6895          NaN              NaN     NaN

[6896 rows x 13 columns]>

In [4]:
data.columns

Index(['page_id', 'name', 'urlslug', 'ID', 'ALIGN', 'EYE', 'HAIR', 'SEX',
       'GSM', 'ALIVE', 'APPEARANCES', 'FIRST APPEARANCE', 'YEAR'],
      dtype='object')

In [5]:
data.info

<bound method DataFrame.info of       page_id                          name  \
0        1422          Batman (Bruce Wayne)
1       23387         Superman (Clark Kent)
2        1458    Green Lantern (Hal Jordan)
3        1659      James Gordon (New Earth)
4        1576   Richard Grayson (New Earth)
...       ...                           ...
6891    66302       Nadine West (New Earth)
6892   283475    Warren Harding (New Earth)
6893   283478  William Harrison (New Earth)
6894   283471  William McKinley (New Earth)
6895   150660            Mookie (New Earth)

                                   urlslug               ID            ALIGN  \
0             \/wiki\/Batman_(Bruce_Wayne)  Secret Identity  Good Characters
1            \/wiki\/Superman_(Clark_Kent)  Secret Identity  Good Characters
2       \/wiki\/Green_Lantern_(Hal_Jordan)  Secret Identity  Good Characters
3         \/wiki\/James_Gordon_(New_Earth)  Public Identity  Good Characters
4      \/wiki\/Richard_Grayson_(New_Earth)  Secret Identity  Good Characters
...                                    ...              ...              ...
6891       \/wiki\/Nadine_West_(New_Earth)  Public Identity  Good Characters
6892    \/wiki\/Warren_Harding_(New_Earth)  Public Identity  Good Characters
6893  \/wiki\/William_Harrison_(New_Earth)  Public Identity  Good Characters
6894  \/wiki\/William_McKinley_(New_Earth)  Public Identity  Good Characters
6895            \/wiki\/Mookie_(New_Earth)  Public Identity   Bad Characters

             EYE        HAIR                SEX  GSM              ALIVE  \
0      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
1      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
2     Brown Eyes  Brown Hair    Male Characters  NaN  Living Characters
3     Brown Eyes  White Hair    Male Characters  NaN  Living Characters
4      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
...          ...         ...                ...  ...                ...
6891         NaN         NaN  Female Characters  NaN  Living Characters
6892         NaN         NaN    Male Characters  NaN  Living Characters
6893         NaN         NaN    Male Characters  NaN  Living Characters
6894         NaN         NaN    Male Characters  NaN  Living Characters
6895   Blue Eyes  Blond Hair    Male Characters  NaN  Living Characters

      APPEARANCES FIRST APPEARANCE    YEAR
0          3093.0        1939, May  1939.0
1          2496.0    1986, October  1986.0
2          1565.0    1959, October  1959.0
3          1316.0   1987, February  1987.0
4          1237.0      1940, April  1940.0
...           ...              ...     ...
6891          NaN              NaN     NaN
6892          NaN              NaN     NaN
6893          NaN              NaN     NaN
6894          NaN              NaN     NaN
6895          NaN              NaN     NaN

[6896 rows x 13 columns]>

In [6]:
data.shape

(6896, 13)

In [7]:
data.describe

<bound method NDFrame.describe of       page_id                          name  \
0        1422          Batman (Bruce Wayne)
1       23387         Superman (Clark Kent)
2        1458    Green Lantern (Hal Jordan)
3        1659      James Gordon (New Earth)
4        1576   Richard Grayson (New Earth)
...       ...                           ...
6891    66302       Nadine West (New Earth)
6892   283475    Warren Harding (New Earth)
6893   283478  William Harrison (New Earth)
6894   283471  William McKinley (New Earth)
6895   150660            Mookie (New Earth)

                                   urlslug               ID            ALIGN  \
0             \/wiki\/Batman_(Bruce_Wayne)  Secret Identity  Good Characters
1            \/wiki\/Superman_(Clark_Kent)  Secret Identity  Good Characters
2       \/wiki\/Green_Lantern_(Hal_Jordan)  Secret Identity  Good Characters
3         \/wiki\/James_Gordon_(New_Earth)  Public Identity  Good Characters
4      \/wiki\/Richard_Grayson_(New_Earth)  Secret Identity  Good Characters
...                                    ...              ...              ...
6891       \/wiki\/Nadine_West_(New_Earth)  Public Identity  Good Characters
6892    \/wiki\/Warren_Harding_(New_Earth)  Public Identity  Good Characters
6893  \/wiki\/William_Harrison_(New_Earth)  Public Identity  Good Characters
6894  \/wiki\/William_McKinley_(New_Earth)  Public Identity  Good Characters
6895            \/wiki\/Mookie_(New_Earth)  Public Identity   Bad Characters

             EYE        HAIR                SEX  GSM              ALIVE  \
0      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
1      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
2     Brown Eyes  Brown Hair    Male Characters  NaN  Living Characters
3     Brown Eyes  White Hair    Male Characters  NaN  Living Characters
4      Blue Eyes  Black Hair    Male Characters  NaN  Living Characters
...          ...         ...                ...  ...                ...
6891         NaN         NaN  Female Characters  NaN  Living Characters
6892         NaN         NaN    Male Characters  NaN  Living Characters
6893         NaN         NaN    Male Characters  NaN  Living Characters
6894         NaN         NaN    Male Characters  NaN  Living Characters
6895   Blue Eyes  Blond Hair    Male Characters  NaN  Living Characters

      APPEARANCES FIRST APPEARANCE    YEAR
0          3093.0        1939, May  1939.0
1          2496.0    1986, October  1986.0
2          1565.0    1959, October  1959.0
3          1316.0   1987, February  1987.0
4          1237.0      1940, April  1940.0
...           ...              ...     ...
6891          NaN              NaN     NaN
6892          NaN              NaN     NaN
6893          NaN              NaN     NaN
6894          NaN              NaN     NaN
6895          NaN              NaN     NaN

[6896 rows x 13 columns]>

In [8]:
data.describe(include='object')

,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,FIRST APPEARANCE
count,6896,6896,4883,6295,3268,4622,6771,64,6893,6827
unique,6896,6896,3,4,17,17,4,2,2,774
top,Batman (Bruce Wayne),\/wiki\/Batman_(Bruce_Wayne),Public Identity,Bad Characters,Blue Eyes,Black Hair,Male Characters,Homosexual Characters,Living Characters,"2010, December"
freq,1,1,2466,2895,1102,1574,4783,54,5200,78