In [1]:
import pandas as pd
data = pd.read_csv('marvel-wikia-data.csv')

In [2]:
data

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,1678,Spider-Man (Peter Parker),\/Spider-Man_(Peter_Parker),Secret Identity,Good Characters,Hazel Eyes,Brown Hair,Male Characters,NaN,Living Characters,4043.0,Aug-62,1962.0
1,7139,Captain America (Steven Rogers),\/Captain_America_(Steven_Rogers),Public Identity,Good Characters,Blue Eyes,White Hair,Male Characters,NaN,Living Characters,3360.0,Mar-41,1941.0
2,64786,"Wolverine (James \""Logan\"" Howlett)",\/Wolverine_(James_%22Logan%22_Howlett),Public Identity,Neutral Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3061.0,Oct-74,1974.0
3,1868,"Iron Man (Anthony \""Tony\"" Stark)",\/Iron_Man_(Anthony_%22Tony%22_Stark),Public Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2961.0,Mar-63,1963.0
4,2460,Thor (Thor Odinson),\/Thor_(Thor_Odinson),No Dual Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,2258.0,Nov-50,1950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16371,657508,Ru'ach (Earth-616),\/Ru%27ach_(Earth-616),No Dual Identity,Bad Characters,Green Eyes,No Hair,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16372,665474,Thane (Thanos' son) (Earth-616),\/Thane_(Thanos%27_son)_(Earth-616),No Dual Identity,Good Characters,Blue Eyes,Bald,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16373,695217,Tinkerer (Skrull) (Earth-616),\/Tinkerer_(Skrull)_(Earth-616),Secret Identity,Bad Characters,Black Eyes,Bald,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16374,708811,TK421 (Spiderling) (Earth-616),\/TK421_(Spiderling)_(Earth-616),Secret Identity,Neutral Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16375,673702,Yologarch (Earth-616),\/Yologarch_(Earth-616),NaN,Bad Characters,NaN,NaN,NaN,NaN,Living Characters,NaN,NaN,NaN

In [3]:
data.head

<bound method NDFrame.head of        page_id                                 name  \
0         1678            Spider-Man (Peter Parker)
1         7139      Captain America (Steven Rogers)
2        64786  Wolverine (James \"Logan\" Howlett)
3         1868    Iron Man (Anthony \"Tony\" Stark)
4         2460                  Thor (Thor Odinson)
...        ...                                  ...
16371   657508                   Ru'ach (Earth-616)
16372   665474      Thane (Thanos' son) (Earth-616)
16373   695217        Tinkerer (Skrull) (Earth-616)
16374   708811       TK421 (Spiderling) (Earth-616)
16375   673702                Yologarch (Earth-616)

                                       urlslug                ID  \
0                  \/Spider-Man_(Peter_Parker)   Secret Identity
1            \/Captain_America_(Steven_Rogers)   Public Identity
2      \/Wolverine_(James_%22Logan%22_Howlett)   Public Identity
3        \/Iron_Man_(Anthony_%22Tony%22_Stark)   Public Identity
4                        \/Thor_(Thor_Odinson)  No Dual Identity
...                                        ...               ...
16371                   \/Ru%27ach_(Earth-616)  No Dual Identity
16372      \/Thane_(Thanos%27_son)_(Earth-616)  No Dual Identity
16373          \/Tinkerer_(Skrull)_(Earth-616)   Secret Identity
16374         \/TK421_(Spiderling)_(Earth-616)   Secret Identity
16375                  \/Yologarch_(Earth-616)               NaN

                    ALIGN         EYE        HAIR              SEX  GSM  \
0         Good Characters  Hazel Eyes  Brown Hair  Male Characters  NaN
1         Good Characters   Blue Eyes  White Hair  Male Characters  NaN
2      Neutral Characters   Blue Eyes  Black Hair  Male Characters  NaN
3         Good Characters   Blue Eyes  Black Hair  Male Characters  NaN
4         Good Characters   Blue Eyes  Blond Hair  Male Characters  NaN
...                   ...         ...         ...              ...  ...
16371      Bad Characters  Green Eyes     No Hair  Male Characters  NaN
16372     Good Characters   Blue Eyes        Bald  Male Characters  NaN
16373      Bad Characters  Black Eyes        Bald  Male Characters  NaN
16374  Neutral Characters         NaN         NaN  Male Characters  NaN
16375      Bad Characters         NaN         NaN              NaN  NaN

                   ALIVE  APPEARANCES FIRST APPEARANCE    Year
0      Living Characters       4043.0           Aug-62  1962.0
1      Living Characters       3360.0           Mar-41  1941.0
2      Living Characters       3061.0           Oct-74  1974.0
3      Living Characters       2961.0           Mar-63  1963.0
4      Living Characters       2258.0           Nov-50  1950.0
...                  ...          ...              ...     ...
16371  Living Characters          NaN              NaN     NaN
16372  Living Characters          NaN              NaN     NaN
16373  Living Characters          NaN              NaN     NaN
16374  Living Characters          NaN              NaN     NaN
16375  Living Characters          NaN              NaN     NaN

[16376 rows x 13 columns]>

In [4]:
data.columns

Index(['page_id', 'name', 'urlslug', 'ID', 'ALIGN', 'EYE', 'HAIR', 'SEX',
       'GSM', 'ALIVE', 'APPEARANCES', 'FIRST APPEARANCE', 'Year'],
      dtype='object')

In [7]:
data.describe

<bound method NDFrame.describe of        page_id                                 name  \
0         1678            Spider-Man (Peter Parker)
1         7139      Captain America (Steven Rogers)
2        64786  Wolverine (James \"Logan\" Howlett)
3         1868    Iron Man (Anthony \"Tony\" Stark)
4         2460                  Thor (Thor Odinson)
...        ...                                  ...
16371   657508                   Ru'ach (Earth-616)
16372   665474      Thane (Thanos' son) (Earth-616)
16373   695217        Tinkerer (Skrull) (Earth-616)
16374   708811       TK421 (Spiderling) (Earth-616)
16375   673702                Yologarch (Earth-616)

                                       urlslug                ID  \
0                  \/Spider-Man_(Peter_Parker)   Secret Identity
1            \/Captain_America_(Steven_Rogers)   Public Identity
2      \/Wolverine_(James_%22Logan%22_Howlett)   Public Identity
3        \/Iron_Man_(Anthony_%22Tony%22_Stark)   Public Identity
4                        \/Thor_(Thor_Odinson)  No Dual Identity
...                                        ...               ...
16371                   \/Ru%27ach_(Earth-616)  No Dual Identity
16372      \/Thane_(Thanos%27_son)_(Earth-616)  No Dual Identity
16373          \/Tinkerer_(Skrull)_(Earth-616)   Secret Identity
16374         \/TK421_(Spiderling)_(Earth-616)   Secret Identity
16375                  \/Yologarch_(Earth-616)               NaN

                    ALIGN         EYE        HAIR              SEX  GSM  \
0         Good Characters  Hazel Eyes  Brown Hair  Male Characters  NaN
1         Good Characters   Blue Eyes  White Hair  Male Characters  NaN
2      Neutral Characters   Blue Eyes  Black Hair  Male Characters  NaN
3         Good Characters   Blue Eyes  Black Hair  Male Characters  NaN
4         Good Characters   Blue Eyes  Blond Hair  Male Characters  NaN
...                   ...         ...         ...              ...  ...
16371      Bad Characters  Green Eyes     No Hair  Male Characters  NaN
16372     Good Characters   Blue Eyes        Bald  Male Characters  NaN
16373      Bad Characters  Black Eyes        Bald  Male Characters  NaN
16374  Neutral Characters         NaN         NaN  Male Characters  NaN
16375      Bad Characters         NaN         NaN              NaN  NaN

                   ALIVE  APPEARANCES FIRST APPEARANCE    Year
0      Living Characters       4043.0           Aug-62  1962.0
1      Living Characters       3360.0           Mar-41  1941.0
2      Living Characters       3061.0           Oct-74  1974.0
3      Living Characters       2961.0           Mar-63  1963.0
4      Living Characters       2258.0           Nov-50  1950.0
...                  ...          ...              ...     ...
16371  Living Characters          NaN              NaN     NaN
16372  Living Characters          NaN              NaN     NaN
16373  Living Characters          NaN              NaN     NaN
16374  Living Characters          NaN              NaN     NaN
16375  Living Characters          NaN              NaN     NaN

[16376 rows x 13 columns]>

In [8]:
data.shape

(16376, 13)

In [9]:
data.info

<bound method DataFrame.info of        page_id                                 name  \
0         1678            Spider-Man (Peter Parker)
1         7139      Captain America (Steven Rogers)
2        64786  Wolverine (James \"Logan\" Howlett)
3         1868    Iron Man (Anthony \"Tony\" Stark)
4         2460                  Thor (Thor Odinson)
...        ...                                  ...
16371   657508                   Ru'ach (Earth-616)
16372   665474      Thane (Thanos' son) (Earth-616)
16373   695217        Tinkerer (Skrull) (Earth-616)
16374   708811       TK421 (Spiderling) (Earth-616)
16375   673702                Yologarch (Earth-616)

                                       urlslug                ID  \
0                  \/Spider-Man_(Peter_Parker)   Secret Identity
1            \/Captain_America_(Steven_Rogers)   Public Identity
2      \/Wolverine_(James_%22Logan%22_Howlett)   Public Identity
3        \/Iron_Man_(Anthony_%22Tony%22_Stark)   Public Identity
4                        \/Thor_(Thor_Odinson)  No Dual Identity
...                                        ...               ...
16371                   \/Ru%27ach_(Earth-616)  No Dual Identity
16372      \/Thane_(Thanos%27_son)_(Earth-616)  No Dual Identity
16373          \/Tinkerer_(Skrull)_(Earth-616)   Secret Identity
16374         \/TK421_(Spiderling)_(Earth-616)   Secret Identity
16375                  \/Yologarch_(Earth-616)               NaN

                    ALIGN         EYE        HAIR              SEX  GSM  \
0         Good Characters  Hazel Eyes  Brown Hair  Male Characters  NaN
1         Good Characters   Blue Eyes  White Hair  Male Characters  NaN
2      Neutral Characters   Blue Eyes  Black Hair  Male Characters  NaN
3         Good Characters   Blue Eyes  Black Hair  Male Characters  NaN
4         Good Characters   Blue Eyes  Blond Hair  Male Characters  NaN
...                   ...         ...         ...              ...  ...
16371      Bad Characters  Green Eyes     No Hair  Male Characters  NaN
16372     Good Characters   Blue Eyes        Bald  Male Characters  NaN
16373      Bad Characters  Black Eyes        Bald  Male Characters  NaN
16374  Neutral Characters         NaN         NaN  Male Characters  NaN
16375      Bad Characters         NaN         NaN              NaN  NaN

                   ALIVE  APPEARANCES FIRST APPEARANCE    Year
0      Living Characters       4043.0           Aug-62  1962.0
1      Living Characters       3360.0           Mar-41  1941.0
2      Living Characters       3061.0           Oct-74  1974.0
3      Living Characters       2961.0           Mar-63  1963.0
4      Living Characters       2258.0           Nov-50  1950.0
...                  ...          ...              ...     ...
16371  Living Characters          NaN              NaN     NaN
16372  Living Characters          NaN              NaN     NaN
16373  Living Characters          NaN              NaN     NaN
16374  Living Characters          NaN              NaN     NaN
16375  Living Characters          NaN              NaN     NaN

[16376 rows x 13 columns]>

In [10]:
data.describe

<bound method NDFrame.describe of        page_id                                 name  \
0         1678            Spider-Man (Peter Parker)
1         7139      Captain America (Steven Rogers)
2        64786  Wolverine (James \"Logan\" Howlett)
3         1868    Iron Man (Anthony \"Tony\" Stark)
4         2460                  Thor (Thor Odinson)
...        ...                                  ...
16371   657508                   Ru'ach (Earth-616)
16372   665474      Thane (Thanos' son) (Earth-616)
16373   695217        Tinkerer (Skrull) (Earth-616)
16374   708811       TK421 (Spiderling) (Earth-616)
16375   673702                Yologarch (Earth-616)

                                       urlslug                ID  \
0                  \/Spider-Man_(Peter_Parker)   Secret Identity
1            \/Captain_America_(Steven_Rogers)   Public Identity
2      \/Wolverine_(James_%22Logan%22_Howlett)   Public Identity
3        \/Iron_Man_(Anthony_%22Tony%22_Stark)   Public Identity
4                        \/Thor_(Thor_Odinson)  No Dual Identity
...                                        ...               ...
16371                   \/Ru%27ach_(Earth-616)  No Dual Identity
16372      \/Thane_(Thanos%27_son)_(Earth-616)  No Dual Identity
16373          \/Tinkerer_(Skrull)_(Earth-616)   Secret Identity
16374         \/TK421_(Spiderling)_(Earth-616)   Secret Identity
16375                  \/Yologarch_(Earth-616)               NaN

                    ALIGN         EYE        HAIR              SEX  GSM  \
0         Good Characters  Hazel Eyes  Brown Hair  Male Characters  NaN
1         Good Characters   Blue Eyes  White Hair  Male Characters  NaN
2      Neutral Characters   Blue Eyes  Black Hair  Male Characters  NaN
3         Good Characters   Blue Eyes  Black Hair  Male Characters  NaN
4         Good Characters   Blue Eyes  Blond Hair  Male Characters  NaN
...                   ...         ...         ...              ...  ...
16371      Bad Characters  Green Eyes     No Hair  Male Characters  NaN
16372     Good Characters   Blue Eyes        Bald  Male Characters  NaN
16373      Bad Characters  Black Eyes        Bald  Male Characters  NaN
16374  Neutral Characters         NaN         NaN  Male Characters  NaN
16375      Bad Characters         NaN         NaN              NaN  NaN

                   ALIVE  APPEARANCES FIRST APPEARANCE    Year
0      Living Characters       4043.0           Aug-62  1962.0
1      Living Characters       3360.0           Mar-41  1941.0
2      Living Characters       3061.0           Oct-74  1974.0
3      Living Characters       2961.0           Mar-63  1963.0
4      Living Characters       2258.0           Nov-50  1950.0
...                  ...          ...              ...     ...
16371  Living Characters          NaN              NaN     NaN
16372  Living Characters          NaN              NaN     NaN
16373  Living Characters          NaN              NaN     NaN
16374  Living Characters          NaN              NaN     NaN
16375  Living Characters          NaN              NaN     NaN

[16376 rows x 13 columns]>

In [11]:
data.describe(include='object')

,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,FIRST APPEARANCE
count,16376,16376,12606,13564,6609,12112,15522,90,16373,15561
unique,16376,16376,4,3,24,25,4,6,2,832
top,Spider-Man (Peter Parker),\/Spider-Man_(Peter_Parker),Secret Identity,Bad Characters,Blue Eyes,Black Hair,Male Characters,Homosexual Characters,Living Characters,Jun-92
freq,1,1,6275,6720,1962,3755,11638,66,12608,72